# GitHub Pages Configuration for AI Agent Launchpad Documentation

title: "AI Agent Launchpad"
description: "Complete Technical Architecture & Flow Documentation for AI Agent Deployment Platform"
url: "https://yourusername.github.io"
baseurl: "/agent-launchpad-infra"

# Theme
theme: minima
remote_theme: pages-themes/cayman@v0.2.0

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Navigation
navigation:
  - title: "Home"
    url: "/"
  - title: "Architecture"
    url: "/architecture"
  - title: "API Reference"
    url: "/api-reference"
  - title: "Security"
    url: "/security"
  - title: "Deployment"
    url: "/deployment"

# Footer
footer:
  text: "AI Agent Launchpad Documentation"
  links:
    - title: "GitHub"
      url: "https://github.com/yourusername/agent-launchpad-infra"
    - title: "Issues"
      url: "https://github.com/yourusername/agent-launchpad-infra/issues"

# SEO
author: "Your Name"
twitter:
  username: "yourusername"
  card: "summary_large_image"

# Google Analytics (optional)
# google_analytics: "UA-XXXXXXXX-X"

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/ 